<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="Slideshow1.css">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Slideshow</title>
</head>
<body>
	<div class="content">
		<div class="slides">
			<input type="radio" name="slide" id="slide1" checked >
			<input type="radio" name="slide" id="slide2">
			<input type="radio" name="slide" id="slide3">
			<input type="radio" name="slide" id="slide4">
			<input type="radio" name="slide" id="slide5">

			<div class="slide s1">
				<img src="./img/1.jpg" alt="Paisagem medieval com montanhas">
			</div>	

			<div class="slide">
				<img src="./img/2.jpg" alt="Paisagem fantasia com arvores roxas">
			</div>
			<div class="slide">
				<img src="./img/3.jpg" alt="capa do jogo cities skylines">
			</div>
			<div class="slide"> 
				<img src="./img/4.jpg" alt="lugar fantasia com cristais e montanhas">
			</div>
			<div class="slide">
				<img src="./img/5.jpg" alt="horizonte escuros com montanhas e céu rosado">
			</div>
		</div>

		<div class="navigation">
			<label class="bar"for = "slide1"></label>
			<label class="bar"for = "slide2"></label>
			<label class="bar"for = "slide3"></label>
			<label class="bar"for = "slide4"></label>
			<label class="bar"for = "slide5"></label>
		</div>
		
	</div>
</body>
</html>


body{
	margin: 0;
	padding: 0;
	height: 100vh;
	width: 100vw;
	background: linear-gradient(72deg, #3DEBB0 1%, #8956F3 99%);
}

.content {
	height: 530px;
	width: 935px;
	border-radius: 20px;
	overflow: hidden;
	position: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%, -50%);
}

.navigation {
	position: absolute;
	bottom: 20px;
	left: 50%;
	transform: translate(-50%);
	display: flex;
}

.bar{
	width: 70px;
	height: 17px;
	border: 2px solid #FFF;
	margin: 6px;
	border-radius: 5px;
	cursor: pointer;
	transition: .4s;
}

.bar:hover{
		background: #fff;
} 

input{
	display: none;
}

.slides{
	display: flex;
	width: 500%;
	height: 100%;
}

.slide{
	width: 20%;
	transition: .6s;
}

.slide img {
	width: 100%;
	height: 100%;
}

#slide1:checked ~ .s1 {
	margin-left: 0;
} 

#slide2:checked ~ .s1 {
	margin-left: -20%;
}

#slide3:checked ~ .s1 {
	margin-left: -40%;
}

#slide4:checked ~ .s1 {
	margin-left: -60%;
}

#slide5:checked ~ .s1 {
	margin-left: -80%;
}
